-- Hito 1B: siembra de ejercicios desde free-exercise-db (dominio publico, Unlicense).
-- Fuente: https://github.com/yuhonas/free-exercise-db (dist/exercises.json), 876 ejercicios.
-- Nombres y grupos musculares quedan en ingles tal cual el dataset; la traduccion a
-- espanol vive en la capa de presentacion (lib/exercises.ts), no en los datos.

insert into public.exercises (name, primary_muscle_group, secondary_muscle_groups, equipment, is_custom)
values
  ('3/4 Sit-Up', 'abdominals', '{}', 'body only', false),
  ('90/90 Hamstring', 'hamstrings', '{"calves"}', 'body only', false),
  ('Ab Crunch Machine', 'abdominals', '{}', 'machine', false),
  ('Ab Roller', 'abdominals', '{"shoulders"}', 'other', false),
  ('Adductor', 'adductors', '{}', 'foam roll', false),
  ('Adductor/Groin', 'adductors', '{}', null, false),
  ('Advanced Kettlebell Windmill', 'abdominals', '{"glutes","hamstrings","shoulders"}', 'kettlebells', false),
  ('Air Bike', 'abdominals', '{}', 'body only', false),
  ('All Fours Quad Stretch', 'quadriceps', '{"quadriceps"}', 'body only', false),
  ('Alternate Hammer Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Alternate Heel Touchers', 'abdominals', '{}', 'body only', false),
  ('Alternate Incline Dumbbell Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Alternate Leg Diagonal Bound', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', null, false),
  ('Alternating Cable Shoulder Press', 'shoulders', '{"triceps"}', 'cable', false),
  ('Alternating Deltoid Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Alternating Floor Press', 'chest', '{"abdominals","shoulders","triceps"}', 'kettlebells', false),
  ('Alternating Hang Clean', 'hamstrings', '{"biceps","calves","forearms","glutes","lower back","traps"}', 'kettlebells', false),
  ('Alternating Kettlebell Press', 'shoulders', '{"triceps"}', 'kettlebells', false),
  ('Alternating Kettlebell Row', 'middle back', '{"biceps","lats"}', 'kettlebells', false),
  ('Alternating Renegade Row', 'middle back', '{"abdominals","biceps","chest","lats","triceps"}', 'kettlebells', false),
  ('Ankle Circles', 'calves', '{}', null, false),
  ('Ankle On The Knee', 'glutes', '{}', null, false),
  ('Anterior Tibialis-SMR', 'calves', '{}', 'other', false),
  ('Anti-Gravity Press', 'shoulders', '{"middle back","traps","triceps"}', 'barbell', false),
  ('Arm Circles', 'shoulders', '{"traps"}', null, false),
  ('Arnold Dumbbell Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Around The Worlds', 'chest', '{"shoulders"}', 'dumbbell', false),
  ('Atlas Stone Trainer', 'lower back', '{"biceps","forearms","glutes","hamstrings","quadriceps"}', 'other', false),
  ('Atlas Stones', 'lower back', '{"abdominals","adductors","biceps","calves","forearms","glutes","hamstrings","middle back","quadriceps","traps"}', 'other', false),
  ('Axle Deadlift', 'lower back', '{"forearms","glutes","hamstrings","middle back","quadriceps","traps"}', 'other', false),
  ('Back Flyes - With Bands', 'shoulders', '{"middle back","triceps"}', 'bands', false),
  ('Backward Drag', 'quadriceps', '{"calves","forearms","glutes","hamstrings","lower back"}', 'other', false),
  ('Backward Medicine Ball Throw', 'shoulders', '{}', 'medicine ball', false),
  ('Balance Board', 'calves', '{"hamstrings","quadriceps"}', 'other', false),
  ('Ball Leg Curl', 'hamstrings', '{"calves","glutes"}', 'exercise ball', false),
  ('Band Assisted Pull-Up', 'lats', '{"abdominals","forearms","middle back"}', 'other', false),
  ('Band Good Morning', 'hamstrings', '{"glutes","lower back"}', 'bands', false),
  ('Band Good Morning (Pull Through)', 'hamstrings', '{"glutes","lower back"}', 'bands', false),
  ('Band Hip Adductions', 'adductors', '{}', 'bands', false),
  ('Band Pull Apart', 'shoulders', '{"middle back","traps"}', 'bands', false),
  ('Band Skull Crusher', 'triceps', '{}', 'bands', false),
  ('Barbell Ab Rollout', 'abdominals', '{"lower back","shoulders"}', 'barbell', false),
  ('Barbell Ab Rollout - On Knees', 'abdominals', '{"lower back","shoulders"}', 'barbell', false),
  ('Barbell Bench Press - Medium Grip', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Barbell Curl', 'biceps', '{"forearms"}', 'barbell', false),
  ('Barbell Curls Lying Against An Incline', 'biceps', '{}', 'barbell', false),
  ('Barbell Deadlift', 'lower back', '{"calves","forearms","glutes","hamstrings","lats","middle back","quadriceps","traps"}', 'barbell', false),
  ('Barbell Full Squat', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Barbell Glute Bridge', 'glutes', '{"calves","hamstrings"}', 'barbell', false),
  ('Barbell Guillotine Bench Press', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Barbell Hack Squat', 'quadriceps', '{"calves","forearms","hamstrings"}', 'barbell', false),
  ('Barbell Hip Thrust', 'glutes', '{"calves","hamstrings"}', 'barbell', false),
  ('Barbell Incline Bench Press - Medium Grip', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Barbell Incline Shoulder Raise', 'shoulders', '{"chest"}', 'barbell', false),
  ('Barbell Lunge', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Barbell Rear Delt Row', 'shoulders', '{"biceps","lats","middle back"}', 'barbell', false),
  ('Barbell Rollout from Bench', 'abdominals', '{"glutes","hamstrings","lats","shoulders"}', 'barbell', false),
  ('Barbell Seated Calf Raise', 'calves', '{}', 'barbell', false),
  ('Barbell Shoulder Press', 'shoulders', '{"chest","triceps"}', 'barbell', false),
  ('Barbell Shrug', 'traps', '{}', 'barbell', false),
  ('Barbell Shrug Behind The Back', 'traps', '{"forearms","middle back"}', 'barbell', false),
  ('Barbell Side Bend', 'abdominals', '{"lower back"}', 'barbell', false),
  ('Barbell Side Split Squat', 'quadriceps', '{"calves","hamstrings","lower back"}', 'barbell', false),
  ('Barbell Squat', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Barbell Squat To A Bench', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Barbell Step Ups', 'quadriceps', '{"calves","glutes","hamstrings","quadriceps"}', 'barbell', false),
  ('Barbell Walking Lunge', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Battling Ropes', 'shoulders', '{"chest","forearms"}', 'other', false),
  ('Bear Crawl Sled Drags', 'quadriceps', '{"calves","glutes","hamstrings"}', 'other', false),
  ('Behind Head Chest Stretch', 'chest', '{"shoulders"}', 'other', false),
  ('Bench Dips', 'triceps', '{"chest","shoulders"}', 'body only', false),
  ('Bench Jump', 'quadriceps', '{"calves","glutes","hamstrings"}', 'body only', false),
  ('Bench Press - Powerlifting', 'triceps', '{"chest","forearms","lats","shoulders"}', 'barbell', false),
  ('Bench Press - With Bands', 'chest', '{"shoulders","triceps"}', 'bands', false),
  ('Bench Press with Chains', 'triceps', '{"chest","lats","shoulders"}', 'barbell', false),
  ('Bench Sprint', 'quadriceps', '{"calves","glutes","hamstrings"}', 'other', false),
  ('Bent-Arm Barbell Pullover', 'lats', '{"chest","lats","shoulders","triceps"}', 'barbell', false),
  ('Bent-Arm Dumbbell Pullover', 'chest', '{"lats","shoulders","triceps"}', 'dumbbell', false),
  ('Bent-Knee Hip Raise', 'abdominals', '{}', 'body only', false),
  ('Bent Over Barbell Row', 'middle back', '{"biceps","lats","shoulders"}', 'barbell', false),
  ('Bent Over Dumbbell Rear Delt Raise With Head On Bench', 'shoulders', '{}', 'dumbbell', false),
  ('Bent Over Low-Pulley Side Lateral', 'shoulders', '{"lower back","middle back","traps"}', 'cable', false),
  ('Bent Over One-Arm Long Bar Row', 'middle back', '{"biceps","lats","lower back","traps"}', 'barbell', false),
  ('Bent Over Two-Arm Long Bar Row', 'middle back', '{"biceps","lats"}', 'barbell', false),
  ('Bent Over Two-Dumbbell Row', 'middle back', '{"biceps","lats","shoulders"}', 'dumbbell', false),
  ('Bent Over Two-Dumbbell Row With Palms In', 'middle back', '{"biceps","lats"}', 'dumbbell', false),
  ('Bent Press', 'abdominals', '{"glutes","hamstrings","lower back","quadriceps","shoulders","triceps"}', 'kettlebells', false),
  ('Bicycling', 'quadriceps', '{"calves","glutes","hamstrings"}', 'other', false),
  ('Bicycling, Stationary', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Board Press', 'triceps', '{"chest","forearms","lats","shoulders"}', 'barbell', false),
  ('Body-Up', 'triceps', '{"abdominals","forearms"}', 'body only', false),
  ('Body Tricep Press', 'triceps', '{}', 'body only', false),
  ('Bodyweight Flyes', 'chest', '{"abdominals","shoulders","triceps"}', 'e-z curl bar', false),
  ('Bodyweight Mid Row', 'middle back', '{"biceps","lats"}', 'other', false),
  ('Bodyweight Squat', 'quadriceps', '{"glutes","hamstrings"}', 'body only', false),
  ('Bodyweight Walking Lunge', 'quadriceps', '{"calves","glutes","hamstrings"}', null, false),
  ('Bosu Ball Cable Crunch With Side Bends', 'abdominals', '{}', 'cable', false),
  ('Bottoms-Up Clean From The Hang Position', 'forearms', '{"biceps","shoulders"}', 'kettlebells', false),
  ('Bottoms Up', 'abdominals', '{}', 'body only', false),
  ('Box Jump (Multiple Response)', 'hamstrings', '{"abductors","adductors","calves","glutes","quadriceps"}', 'other', false),
  ('Box Skip', 'hamstrings', '{"abductors","adductors","calves","glutes","quadriceps"}', 'other', false),
  ('Box Squat', 'quadriceps', '{"adductors","calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Box Squat with Bands', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Box Squat with Chains', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Brachialis-SMR', 'biceps', '{}', 'foam roll', false),
  ('Bradford/Rocky Presses', 'shoulders', '{"triceps"}', 'barbell', false),
  ('Butt-Ups', 'abdominals', '{}', 'body only', false),
  ('Butt Lift (Bridge)', 'glutes', '{"hamstrings"}', 'body only', false),
  ('Butterfly', 'chest', '{}', 'machine', false),
  ('Cable Chest Press', 'chest', '{"shoulders","triceps"}', 'cable', false),
  ('Cable Crossover', 'chest', '{"shoulders"}', 'cable', false),
  ('Cable Crunch', 'abdominals', '{}', 'cable', false),
  ('Cable Deadlifts', 'quadriceps', '{"forearms","glutes","hamstrings","lower back"}', 'cable', false),
  ('Cable Hammer Curls - Rope Attachment', 'biceps', '{}', 'cable', false),
  ('Cable Hip Adduction', 'quadriceps', '{}', 'cable', false),
  ('Cable Incline Pushdown', 'lats', '{}', 'cable', false),
  ('Cable Incline Triceps Extension', 'triceps', '{}', 'cable', false),
  ('Cable Internal Rotation', 'shoulders', '{}', 'cable', false),
  ('Cable Iron Cross', 'chest', '{}', 'cable', false),
  ('Cable Judo Flip', 'abdominals', '{}', 'cable', false),
  ('Cable Lying Triceps Extension', 'triceps', '{}', 'cable', false),
  ('Cable One Arm Tricep Extension', 'triceps', '{}', 'cable', false),
  ('Cable Preacher Curl', 'biceps', '{"forearms"}', 'cable', false),
  ('Cable Rear Delt Fly', 'shoulders', '{}', 'cable', false),
  ('Cable Reverse Crunch', 'abdominals', '{}', 'cable', false),
  ('Cable Rope Overhead Triceps Extension', 'triceps', '{}', 'cable', false),
  ('Cable Rope Rear-Delt Rows', 'shoulders', '{"biceps","middle back"}', 'cable', false),
  ('Cable Russian Twists', 'abdominals', '{}', 'cable', false),
  ('Cable Seated Crunch', 'abdominals', '{}', 'cable', false),
  ('Cable Seated Lateral Raise', 'shoulders', '{"middle back","traps"}', 'cable', false),
  ('Cable Shoulder Press', 'shoulders', '{"triceps"}', 'cable', false),
  ('Cable Shrugs', 'traps', '{}', 'cable', false),
  ('Cable Wrist Curl', 'forearms', '{}', 'cable', false),
  ('Calf-Machine Shoulder Shrug', 'traps', '{}', 'machine', false),
  ('Calf Press', 'calves', '{}', 'machine', false),
  ('Calf Press On The Leg Press Machine', 'calves', '{}', 'machine', false),
  ('Calf Raise On A Dumbbell', 'calves', '{}', 'dumbbell', false),
  ('Calf Raises - With Bands', 'calves', '{}', 'bands', false),
  ('Calf Stretch Elbows Against Wall', 'calves', '{}', null, false),
  ('Calf Stretch Hands Against Wall', 'calves', '{}', null, false),
  ('Calves-SMR', 'calves', '{}', 'foam roll', false),
  ('Car Deadlift', 'quadriceps', '{"forearms","glutes","hamstrings","lower back","traps"}', 'other', false),
  ('Car Drivers', 'shoulders', '{"forearms"}', 'barbell', false),
  ('Carioca Quick Step', 'adductors', '{"abdominals","abductors","calves","glutes","hamstrings","quadriceps"}', null, false),
  ('Cat Stretch', 'lower back', '{"middle back","traps"}', null, false),
  ('Catch and Overhead Throw', 'lats', '{"abdominals","chest","shoulders"}', 'medicine ball', false),
  ('Chain Handle Extension', 'triceps', '{}', 'other', false),
  ('Chain Press', 'chest', '{"shoulders","triceps"}', 'other', false),
  ('Chair Leg Extended Stretch', 'hamstrings', '{"adductors"}', 'other', false),
  ('Chair Lower Back Stretch', 'lats', '{"lower back"}', null, false),
  ('Chair Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Chair Upper Body Stretch', 'shoulders', '{"biceps","chest"}', 'other', false),
  ('Chest And Front Of Shoulder Stretch', 'chest', '{"shoulders"}', 'other', false),
  ('Chest Push from 3 point stance', 'chest', '{"abdominals","shoulders","triceps"}', 'medicine ball', false),
  ('Chest Push (multiple response)', 'chest', '{"abdominals","shoulders","triceps"}', 'medicine ball', false),
  ('Chest Push (single response)', 'chest', '{"abdominals","shoulders","triceps"}', 'medicine ball', false),
  ('Chest Push with Run Release', 'chest', '{"abdominals","shoulders","triceps"}', 'medicine ball', false),
  ('Chest Stretch on Stability Ball', 'chest', '{}', 'exercise ball', false),
  ('Child''s Pose', 'lower back', '{"glutes","middle back"}', null, false),
  ('Chin-Up', 'lats', '{"biceps","forearms","middle back"}', 'body only', false),
  ('Chin To Chest Stretch', 'neck', '{"traps"}', null, false),
  ('Circus Bell', 'shoulders', '{"forearms","glutes","hamstrings","lower back","traps","triceps"}', 'other', false),
  ('Clean', 'hamstrings', '{"calves","forearms","glutes","lower back","quadriceps","shoulders","traps"}', 'barbell', false),
  ('Clean Deadlift', 'hamstrings', '{"forearms","glutes","lower back","middle back","quadriceps","traps"}', 'barbell', false),
  ('Clean Pull', 'quadriceps', '{"forearms","glutes","hamstrings","lower back","traps"}', 'barbell', false),
  ('Clean Shrug', 'traps', '{"forearms","shoulders"}', 'barbell', false),
  ('Clean and Jerk', 'shoulders', '{"abdominals","glutes","hamstrings","lower back","quadriceps","traps","triceps"}', 'barbell', false),
  ('Clean and Press', 'shoulders', '{"abdominals","calves","glutes","hamstrings","lower back","middle back","quadriceps","shoulders","traps","triceps"}', 'barbell', false),
  ('Clean from Blocks', 'quadriceps', '{"calves","glutes","hamstrings","shoulders","traps"}', 'barbell', false),
  ('Clock Push-Up', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Close-Grip Barbell Bench Press', 'triceps', '{"chest","shoulders"}', 'barbell', false),
  ('Close-Grip Dumbbell Press', 'triceps', '{"chest","shoulders"}', 'dumbbell', false),
  ('Close-Grip EZ-Bar Curl with Band', 'biceps', '{"forearms"}', 'e-z curl bar', false),
  ('Close-Grip EZ-Bar Press', 'triceps', '{"chest","shoulders"}', 'e-z curl bar', false),
  ('Close-Grip EZ Bar Curl', 'biceps', '{"forearms"}', 'barbell', false),
  ('Close-Grip Front Lat Pulldown', 'lats', '{"biceps","middle back","shoulders"}', 'cable', false),
  ('Close-Grip Push-Up off of a Dumbbell', 'triceps', '{"abdominals","chest","shoulders"}', 'body only', false),
  ('Close-Grip Standing Barbell Curl', 'biceps', '{"forearms"}', 'barbell', false),
  ('Cocoons', 'abdominals', '{}', 'body only', false),
  ('Conan''s Wheel', 'quadriceps', '{"abdominals","biceps","calves","forearms","lower back","shoulders","traps"}', 'other', false),
  ('Concentration Curls', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Cross-Body Crunch', 'abdominals', '{}', 'body only', false),
  ('Cross Body Hammer Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Cross Over - With Bands', 'chest', '{"biceps","shoulders"}', 'bands', false),
  ('Crossover Reverse Lunge', 'lower back', '{"abdominals","abductors","glutes","hamstrings","quadriceps"}', null, false),
  ('Crucifix', 'shoulders', '{"forearms"}', 'other', false),
  ('Crunch - Hands Overhead', 'abdominals', '{}', 'body only', false),
  ('Crunch - Legs On Exercise Ball', 'abdominals', '{}', 'body only', false),
  ('Crunches', 'abdominals', '{}', 'body only', false),
  ('Cuban Press', 'shoulders', '{"traps"}', 'dumbbell', false),
  ('Dancer''s Stretch', 'lower back', '{"abductors","glutes"}', null, false),
  ('Dead Bug', 'abdominals', '{}', 'body only', false),
  ('Deadlift with Bands', 'lower back', '{"forearms","glutes","hamstrings","middle back","quadriceps","traps"}', 'barbell', false),
  ('Deadlift with Chains', 'lower back', '{"forearms","glutes","hamstrings","middle back","quadriceps","traps"}', 'barbell', false),
  ('Decline Barbell Bench Press', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Decline Close-Grip Bench To Skull Crusher', 'triceps', '{"chest","shoulders"}', 'barbell', false),
  ('Decline Crunch', 'abdominals', '{}', 'body only', false),
  ('Decline Dumbbell Bench Press', 'chest', '{"shoulders","triceps"}', 'dumbbell', false),
  ('Decline Dumbbell Flyes', 'chest', '{}', 'dumbbell', false),
  ('Decline Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('Decline EZ Bar Triceps Extension', 'triceps', '{}', 'barbell', false),
  ('Decline Oblique Crunch', 'abdominals', '{}', 'body only', false),
  ('Decline Push-Up', 'chest', '{"shoulders","triceps"}', null, false),
  ('Decline Reverse Crunch', 'abdominals', '{}', 'body only', false),
  ('Decline Smith Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Deficit Deadlift', 'lower back', '{"forearms","glutes","hamstrings","middle back","quadriceps","traps"}', 'barbell', false),
  ('Depth Jump Leap', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', 'other', false),
  ('Dip Machine', 'triceps', '{"chest","shoulders"}', 'machine', false),
  ('Dips - Chest Version', 'chest', '{"shoulders","triceps"}', 'other', false),
  ('Dips - Triceps Version', 'triceps', '{"chest","shoulders"}', 'body only', false),
  ('Donkey Calf Raises', 'calves', '{}', 'other', false),
  ('Double Kettlebell Alternating Hang Clean', 'hamstrings', '{"biceps","calves","forearms","glutes","lower back","quadriceps","traps"}', 'kettlebells', false),
  ('Double Kettlebell Jerk', 'shoulders', '{"calves","quadriceps","triceps"}', 'kettlebells', false),
  ('Double Kettlebell Push Press', 'shoulders', '{"calves","quadriceps","triceps"}', 'kettlebells', false),
  ('Double Kettlebell Snatch', 'shoulders', '{"glutes","hamstrings","quadriceps"}', 'kettlebells', false),
  ('Double Kettlebell Windmill', 'abdominals', '{"glutes","hamstrings","shoulders","triceps"}', 'kettlebells', false),
  ('Double Leg Butt Kick', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', 'body only', false),
  ('Downward Facing Balance', 'glutes', '{"abdominals","hamstrings"}', 'exercise ball', false),
  ('Drag Curl', 'biceps', '{"forearms"}', 'barbell', false),
  ('Drop Push', 'chest', '{"shoulders","triceps"}', 'other', false),
  ('Dumbbell Alternate Bicep Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Dumbbell Bench Press', 'chest', '{"shoulders","triceps"}', 'dumbbell', false),
  ('Dumbbell Bench Press with Neutral Grip', 'chest', '{"shoulders","triceps"}', 'dumbbell', false),
  ('Dumbbell Bicep Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Dumbbell Clean', 'hamstrings', '{"calves","forearms","glutes","lower back","quadriceps","shoulders","traps"}', 'dumbbell', false),
  ('Dumbbell Floor Press', 'triceps', '{"chest","shoulders"}', 'dumbbell', false),
  ('Dumbbell Flyes', 'chest', '{}', 'dumbbell', false),
  ('Dumbbell Incline Row', 'middle back', '{"biceps","forearms","lats","shoulders"}', 'dumbbell', false),
  ('Dumbbell Incline Shoulder Raise', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Dumbbell Lunges', 'quadriceps', '{"calves","glutes","hamstrings"}', 'dumbbell', false),
  ('Dumbbell Lying One-Arm Rear Lateral Raise', 'shoulders', '{"middle back"}', 'dumbbell', false),
  ('Dumbbell Lying Pronation', 'forearms', '{}', 'dumbbell', false),
  ('Dumbbell Lying Rear Lateral Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Dumbbell Lying Supination', 'forearms', '{}', 'dumbbell', false),
  ('Dumbbell One-Arm Shoulder Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Dumbbell One-Arm Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('Dumbbell One-Arm Upright Row', 'shoulders', '{"biceps","traps"}', 'dumbbell', false),
  ('Dumbbell Prone Incline Curl', 'biceps', '{}', 'dumbbell', false),
  ('Dumbbell Raise', 'shoulders', '{"biceps"}', 'dumbbell', false),
  ('Dumbbell Rear Lunge', 'quadriceps', '{"calves","glutes","hamstrings"}', 'dumbbell', false),
  ('Dumbbell Scaption', 'shoulders', '{"traps"}', 'dumbbell', false),
  ('Dumbbell Seated Box Jump', 'quadriceps', '{"calves","glutes","hamstrings"}', 'dumbbell', false),
  ('Dumbbell Seated One-Leg Calf Raise', 'calves', '{}', 'dumbbell', false),
  ('Dumbbell Shoulder Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Dumbbell Shrug', 'traps', '{}', 'dumbbell', false),
  ('Dumbbell Side Bend', 'abdominals', '{}', 'dumbbell', false),
  ('Dumbbell Squat', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'dumbbell', false),
  ('Dumbbell Squat To A Bench', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'dumbbell', false),
  ('Dumbbell Step Ups', 'quadriceps', '{"calves","glutes","hamstrings"}', 'dumbbell', false),
  ('Dumbbell Tricep Extension -Pronated Grip', 'triceps', '{}', 'dumbbell', false),
  ('Dynamic Back Stretch', 'lats', '{}', null, false),
  ('Dynamic Chest Stretch', 'chest', '{"middle back"}', null, false),
  ('EZ-Bar Curl', 'biceps', '{}', 'e-z curl bar', false),
  ('EZ-Bar Skullcrusher', 'triceps', '{"forearms"}', 'e-z curl bar', false),
  ('Elbow Circles', 'shoulders', '{"traps"}', null, false),
  ('Elbow to Knee', 'abdominals', '{}', 'body only', false),
  ('Elbows Back', 'chest', '{"shoulders"}', null, false),
  ('Elevated Back Lunge', 'quadriceps', '{"glutes","hamstrings"}', 'barbell', false),
  ('Elevated Cable Rows', 'lats', '{"middle back","traps"}', 'cable', false),
  ('Elliptical Trainer', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Exercise Ball Crunch', 'abdominals', '{}', 'exercise ball', false),
  ('Exercise Ball Pull-In', 'abdominals', '{}', 'exercise ball', false),
  ('Extended Range One-Arm Kettlebell Floor Press', 'chest', '{"shoulders","triceps"}', 'kettlebells', false),
  ('External Rotation', 'shoulders', '{}', 'dumbbell', false),
  ('External Rotation with Band', 'shoulders', '{}', 'bands', false),
  ('External Rotation with Cable', 'shoulders', '{}', 'cable', false),
  ('Face Pull', 'shoulders', '{"middle back"}', 'cable', false),
  ('Farmer''s Walk', 'forearms', '{"abdominals","glutes","hamstrings","lower back","quadriceps","traps"}', 'other', false),
  ('Fast Skipping', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', 'body only', false),
  ('Finger Curls', 'forearms', '{}', 'barbell', false),
  ('Flat Bench Cable Flyes', 'chest', '{}', 'cable', false),
  ('Flat Bench Leg Pull-In', 'abdominals', '{}', 'body only', false),
  ('Flat Bench Lying Leg Raise', 'abdominals', '{}', 'body only', false),
  ('Flexor Incline Dumbbell Curls', 'biceps', '{}', 'dumbbell', false),
  ('Floor Glute-Ham Raise', 'hamstrings', '{"calves","glutes"}', null, false),
  ('Floor Press', 'triceps', '{"chest","shoulders"}', 'barbell', false),
  ('Floor Press with Chains', 'triceps', '{"chest","shoulders"}', 'barbell', false),
  ('Flutter Kicks', 'glutes', '{"hamstrings"}', 'body only', false),
  ('Foot-SMR', 'calves', '{}', 'other', false),
  ('Forward Drag with Press', 'chest', '{"calves","glutes","hamstrings","quadriceps","shoulders","triceps"}', 'other', false),
  ('Frankenstein Squat', 'quadriceps', '{"abdominals","calves","glutes","hamstrings"}', 'barbell', false),
  ('Freehand Jump Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'body only', false),
  ('Frog Hops', 'quadriceps', '{"calves","glutes","hamstrings"}', null, false),
  ('Frog Sit-Ups', 'abdominals', '{}', 'body only', false),
  ('Front Barbell Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Front Barbell Squat To A Bench', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Front Box Jump', 'hamstrings', '{"abductors","adductors","calves","glutes","quadriceps"}', 'other', false),
  ('Front Cable Raise', 'shoulders', '{}', 'cable', false),
  ('Front Cone Hops (or hurdle hops)', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', 'other', false),
  ('Front Dumbbell Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Front Incline Dumbbell Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Front Leg Raises', 'hamstrings', '{}', 'body only', false),
  ('Front Plate Raise', 'shoulders', '{}', 'other', false),
  ('Front Raise And Pullover', 'chest', '{"lats","shoulders","triceps"}', 'barbell', false),
  ('Front Squat (Clean Grip)', 'quadriceps', '{"abdominals","glutes","hamstrings"}', 'barbell', false),
  ('Front Squats With Two Kettlebells', 'quadriceps', '{"calves","glutes"}', 'kettlebells', false),
  ('Front Two-Dumbbell Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Full Range-Of-Motion Lat Pulldown', 'lats', '{"biceps","middle back","shoulders"}', 'cable', false),
  ('Gironda Sternum Chins', 'lats', '{"biceps","middle back"}', 'other', false),
  ('Glute Ham Raise', 'hamstrings', '{"calves","glutes"}', 'machine', false),
  ('Glute Kickback', 'glutes', '{"hamstrings"}', 'body only', false),
  ('Goblet Squat', 'quadriceps', '{"calves","glutes","hamstrings","shoulders"}', 'kettlebells', false),
  ('Good Morning', 'hamstrings', '{"abdominals","glutes","lower back"}', 'barbell', false),
  ('Good Morning off Pins', 'hamstrings', '{"abdominals","glutes","lower back"}', 'barbell', false),
  ('Gorilla Chin/Crunch', 'abdominals', '{"biceps","lats"}', 'body only', false),
  ('Groin and Back Stretch', 'adductors', '{}', null, false),
  ('Groiners', 'adductors', '{}', 'body only', false),
  ('Hack Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Hammer Curls', 'biceps', '{}', 'dumbbell', false),
  ('Hammer Grip Incline DB Bench Press', 'chest', '{"shoulders","triceps"}', 'dumbbell', false),
  ('Hamstring-SMR', 'hamstrings', '{}', 'foam roll', false),
  ('Hamstring Stretch', 'hamstrings', '{}', null, false),
  ('Handstand Push-Ups', 'shoulders', '{"triceps"}', 'body only', false),
  ('Hang Clean', 'quadriceps', '{"calves","forearms","glutes","hamstrings","lower back","shoulders","traps"}', 'barbell', false),
  ('Hang Clean - Below the Knees', 'quadriceps', '{"calves","forearms","glutes","hamstrings","lower back","shoulders","traps"}', 'barbell', false),
  ('Hang Snatch', 'hamstrings', '{"abdominals","calves","forearms","glutes","lower back","quadriceps","shoulders","traps"}', 'barbell', false),
  ('Hang Snatch - Below Knees', 'hamstrings', '{"abdominals","calves","forearms","glutes","lower back","quadriceps","shoulders","traps"}', 'barbell', false),
  ('Hanging Bar Good Morning', 'hamstrings', '{"abdominals","glutes","lower back"}', 'barbell', false),
  ('Hanging Leg Raise', 'abdominals', '{}', 'body only', false),
  ('Hanging Pike', 'abdominals', '{}', 'body only', false),
  ('Heaving Snatch Balance', 'quadriceps', '{"abdominals","forearms","glutes","hamstrings","shoulders","triceps"}', 'barbell', false),
  ('Heavy Bag Thrust', 'chest', '{"abdominals","shoulders","triceps"}', 'other', false),
  ('High Cable Curls', 'biceps', '{}', 'cable', false),
  ('Hip Circles (prone)', 'abductors', '{"adductors"}', 'body only', false),
  ('Hip Extension with Bands', 'glutes', '{"hamstrings"}', 'bands', false),
  ('Hip Flexion with Band', 'quadriceps', '{}', 'bands', false),
  ('Hip Lift with Band', 'glutes', '{"calves","hamstrings"}', 'bands', false),
  ('Hug A Ball', 'lower back', '{"calves","glutes"}', 'exercise ball', false),
  ('Hug Knees To Chest', 'lower back', '{"glutes"}', null, false),
  ('Hurdle Hops', 'hamstrings', '{"abductors","adductors","calves","glutes","hamstrings"}', 'other', false),
  ('Hyperextensions (Back Extensions)', 'lower back', '{"glutes","hamstrings"}', 'other', false),
  ('Hyperextensions With No Hyperextension Bench', 'lower back', '{"glutes","hamstrings"}', 'body only', false),
  ('IT Band and Glute Stretch', 'abductors', '{}', 'other', false),
  ('Iliotibial Tract-SMR', 'abductors', '{}', 'foam roll', false),
  ('Inchworm', 'hamstrings', '{}', 'body only', false),
  ('Incline Barbell Triceps Extension', 'triceps', '{"forearms"}', 'barbell', false),
  ('Incline Bench Pull', 'middle back', '{"lats","shoulders"}', 'barbell', false),
  ('Incline Cable Chest Press', 'chest', '{"shoulders","triceps"}', 'cable', false),
  ('Incline Cable Flye', 'chest', '{"shoulders"}', 'cable', false),
  ('Incline Dumbbell Bench With Palms Facing In', 'chest', '{"shoulders","triceps"}', 'dumbbell', false),
  ('Incline Dumbbell Curl', 'biceps', '{}', 'dumbbell', false),
  ('Incline Dumbbell Flyes', 'chest', '{"shoulders"}', 'dumbbell', false),
  ('Incline Dumbbell Flyes - With A Twist', 'chest', '{"shoulders"}', 'dumbbell', false),
  ('Incline Dumbbell Press', 'chest', '{"shoulders","triceps"}', 'dumbbell', false),
  ('Incline Hammer Curls', 'biceps', '{}', 'dumbbell', false),
  ('Incline Inner Biceps Curl', 'biceps', '{}', 'dumbbell', false),
  ('Incline Push-Up', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Incline Push-Up Close-Grip', 'triceps', '{"chest","shoulders"}', 'body only', false),
  ('Incline Push-Up Depth Jump', 'chest', '{"shoulders","triceps"}', 'other', false),
  ('Incline Push-Up Medium', 'chest', '{"abdominals","shoulders","triceps"}', 'body only', false),
  ('Incline Push-Up Reverse Grip', 'chest', '{"abdominals","shoulders","triceps"}', 'body only', false),
  ('Incline Push-Up Wide', 'chest', '{"abdominals","shoulders","triceps"}', 'body only', false),
  ('Intermediate Groin Stretch', 'hamstrings', '{}', 'other', false),
  ('Intermediate Hip Flexor and Quad Stretch', 'quadriceps', '{}', 'other', false),
  ('Internal Rotation with Band', 'shoulders', '{}', 'bands', false),
  ('Inverted Row', 'middle back', '{"lats"}', null, false),
  ('Inverted Row with Straps', 'middle back', '{"biceps","lats"}', 'other', false),
  ('Iron Cross', 'shoulders', '{"chest","glutes","hamstrings","lower back","quadriceps","traps"}', 'dumbbell', false),
  ('Iron Crosses (stretch)', 'quadriceps', '{}', null, false),
  ('Isometric Chest Squeezes', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Isometric Neck Exercise - Front And Back', 'neck', '{}', 'body only', false),
  ('Isometric Neck Exercise - Sides', 'neck', '{}', 'body only', false),
  ('Isometric Wipers', 'chest', '{"abdominals","shoulders","triceps"}', 'body only', false),
  ('JM Press', 'triceps', '{"chest","shoulders"}', 'barbell', false),
  ('Jackknife Sit-Up', 'abdominals', '{}', 'body only', false),
  ('Janda Sit-Up', 'abdominals', '{}', 'body only', false),
  ('Jefferson Squats', 'quadriceps', '{"calves","glutes","hamstrings","lower back","traps"}', 'barbell', false),
  ('Jerk Balance', 'shoulders', '{"glutes","hamstrings","quadriceps","triceps"}', 'barbell', false),
  ('Jerk Dip Squat', 'quadriceps', '{"abdominals","calves"}', 'barbell', false),
  ('Jogging, Treadmill', 'quadriceps', '{"glutes","hamstrings"}', 'machine', false),
  ('Keg Load', 'lower back', '{"abdominals","biceps","calves","forearms","glutes","hamstrings","middle back","quadriceps","shoulders","traps"}', 'other', false),
  ('Kettlebell Arnold Press', 'shoulders', '{"triceps"}', 'kettlebells', false),
  ('Kettlebell Dead Clean', 'hamstrings', '{"calves","glutes","lower back","quadriceps","traps"}', 'kettlebells', false),
  ('Kettlebell Figure 8', 'abdominals', '{"hamstrings","shoulders"}', 'kettlebells', false),
  ('Kettlebell Halo', 'shoulders', '{"traps","middle back","abdominals","triceps"}', 'kettlebells', false),
  ('Kettlebell Halo with Overhead Extension', 'shoulders', '{"triceps","traps","middle back","abdominals"}', 'kettlebells', false),
  ('Kettlebell Hang Clean', 'hamstrings', '{"calves","glutes","lower back","shoulders","traps"}', 'kettlebells', false),
  ('Kettlebell One-Legged Deadlift', 'hamstrings', '{"glutes","lower back"}', 'kettlebells', false),
  ('Kettlebell Overhead Triceps Extension', 'triceps', '{"shoulders","abdominals"}', 'kettlebells', false),
  ('Kettlebell Pass Between The Legs', 'abdominals', '{"glutes","hamstrings","shoulders"}', 'kettlebells', false),
  ('Kettlebell Pirate Ships', 'shoulders', '{"abdominals"}', 'kettlebells', false),
  ('Kettlebell Pistol Squat', 'quadriceps', '{"calves","glutes","hamstrings","shoulders"}', 'kettlebells', false),
  ('Kettlebell Seated Press', 'shoulders', '{"triceps"}', 'kettlebells', false),
  ('Kettlebell Seesaw Press', 'shoulders', '{"triceps"}', 'kettlebells', false),
  ('Kettlebell Sumo High Pull', 'traps', '{"adductors","glutes","hamstrings","quadriceps","shoulders"}', 'kettlebells', false),
  ('Kettlebell Thruster', 'shoulders', '{"quadriceps","triceps"}', 'kettlebells', false),
  ('Kettlebell Turkish Get-Up (Lunge style)', 'shoulders', '{"abdominals","hamstrings","quadriceps","triceps"}', 'kettlebells', false),
  ('Kettlebell Turkish Get-Up (Squat style)', 'shoulders', '{"abdominals","calves","hamstrings","quadriceps","triceps"}', 'kettlebells', false),
  ('Kettlebell Windmill', 'abdominals', '{"glutes","hamstrings","shoulders","triceps"}', 'kettlebells', false),
  ('Kipping Muscle Up', 'lats', '{"abdominals","biceps","forearms","middle back","shoulders","traps","triceps"}', 'other', false),
  ('Knee Across The Body', 'glutes', '{"abductors","lower back"}', null, false),
  ('Knee Circles', 'calves', '{"hamstrings","quadriceps"}', 'body only', false),
  ('Knee/Hip Raise On Parallel Bars', 'abdominals', '{}', 'other', false),
  ('Knee Tuck Jump', 'hamstrings', '{"abductors","adductors","calves","glutes","quadriceps"}', 'body only', false),
  ('Kneeling Arm Drill', 'shoulders', '{"abdominals"}', null, false),
  ('Kneeling Cable Crunch With Alternating Oblique Twists', 'abdominals', '{}', 'cable', false),
  ('Kneeling Cable Triceps Extension', 'triceps', '{}', 'cable', false),
  ('Kneeling Forearm Stretch', 'forearms', '{}', null, false),
  ('Kneeling High Pulley Row', 'lats', '{"biceps","middle back"}', 'cable', false),
  ('Kneeling Hip Flexor', 'quadriceps', '{"quadriceps"}', null, false),
  ('Kneeling Jump Squat', 'glutes', '{"calves","hamstrings","quadriceps"}', 'barbell', false),
  ('Kneeling Single-Arm High Pulley Row', 'lats', '{"biceps","middle back"}', 'cable', false),
  ('Kneeling Squat', 'glutes', '{"abdominals","hamstrings","lower back"}', 'barbell', false),
  ('Landmine 180''s', 'abdominals', '{"glutes","lower back","shoulders"}', 'barbell', false),
  ('Landmine Linear Jammer', 'shoulders', '{"abdominals","calves","chest","hamstrings","quadriceps","triceps"}', 'barbell', false),
  ('Lateral Bound', 'adductors', '{"abductors","calves","glutes","hamstrings","quadriceps"}', 'body only', false),
  ('Lateral Box Jump', 'adductors', '{"abductors","calves","glutes","hamstrings","quadriceps"}', 'other', false),
  ('Lateral Cone Hops', 'adductors', '{"abductors","calves","glutes","hamstrings","quadriceps"}', 'other', false),
  ('Lateral Raise - With Bands', 'shoulders', '{}', 'bands', false),
  ('Latissimus Dorsi-SMR', 'lats', '{}', 'foam roll', false),
  ('Leg-Over Floor Press', 'chest', '{"shoulders","triceps"}', 'kettlebells', false),
  ('Leg-Up Hamstring Stretch', 'hamstrings', '{}', null, false),
  ('Leg Extensions', 'quadriceps', '{}', 'machine', false),
  ('Leg Lift', 'glutes', '{"hamstrings"}', 'body only', false),
  ('Leg Press', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Leg Pull-In', 'abdominals', '{}', 'body only', false),
  ('Leverage Chest Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Leverage Deadlift', 'quadriceps', '{"glutes","hamstrings"}', 'machine', false),
  ('Leverage Decline Chest Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Leverage High Row', 'middle back', '{"lats"}', 'machine', false),
  ('Leverage Incline Chest Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Leverage Iso Row', 'lats', '{"biceps","middle back"}', 'machine', false),
  ('Leverage Shoulder Press', 'shoulders', '{"triceps"}', 'machine', false),
  ('Leverage Shrug', 'traps', '{"forearms"}', 'machine', false),
  ('Linear 3-Part Start Technique', 'hamstrings', '{"calves","quadriceps"}', null, false),
  ('Linear Acceleration Wall Drill', 'hamstrings', '{"calves","glutes","quadriceps"}', null, false),
  ('Linear Depth Jump', 'quadriceps', '{"calves","glutes","hamstrings"}', 'other', false),
  ('Log Lift', 'shoulders', '{"abdominals","chest","glutes","hamstrings","lower back","middle back","quadriceps","traps","triceps"}', 'other', false),
  ('London Bridges', 'lats', '{"biceps","forearms","middle back"}', 'other', false),
  ('Looking At Ceiling', 'quadriceps', '{}', null, false),
  ('Low Cable Crossover', 'chest', '{"shoulders"}', 'cable', false),
  ('Low Cable Triceps Extension', 'triceps', '{}', 'cable', false),
  ('Low Pulley Row To Neck', 'shoulders', '{"biceps","middle back","traps"}', 'cable', false),
  ('Lower Back-SMR', 'lower back', '{}', 'foam roll', false),
  ('Lower Back Curl', 'abdominals', '{}', 'body only', false),
  ('Lunge Pass Through', 'hamstrings', '{"calves","glutes","quadriceps"}', 'kettlebells', false),
  ('Lunge Sprint', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Lying Bent Leg Groin', 'adductors', '{}', 'other', false),
  ('Lying Cable Curl', 'biceps', '{}', 'cable', false),
  ('Lying Cambered Barbell Row', 'middle back', '{"biceps","lats","traps"}', 'barbell', false),
  ('Lying Close-Grip Bar Curl On High Pulley', 'biceps', '{}', 'cable', false),
  ('Lying Close-Grip Barbell Triceps Extension Behind The Head', 'triceps', '{}', 'barbell', false),
  ('Lying Close-Grip Barbell Triceps Press To Chin', 'triceps', '{}', 'e-z curl bar', false),
  ('Lying Crossover', 'abductors', '{}', 'body only', false),
  ('Lying Dumbbell Tricep Extension', 'triceps', '{"chest","shoulders"}', 'dumbbell', false),
  ('Lying Face Down Plate Neck Resistance', 'neck', '{}', 'other', false),
  ('Lying Face Up Plate Neck Resistance', 'neck', '{}', 'other', false),
  ('Lying Glute', 'glutes', '{"abductors"}', 'body only', false),
  ('Lying Hamstring', 'hamstrings', '{"calves"}', 'other', false),
  ('Lying High Bench Barbell Curl', 'biceps', '{}', 'barbell', false),
  ('Lying Leg Curls', 'hamstrings', '{}', 'machine', false),
  ('Lying Machine Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Lying One-Arm Lateral Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Lying Prone Quadriceps', 'quadriceps', '{}', 'body only', false),
  ('Lying Rear Delt Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Lying Supine Dumbbell Curl', 'biceps', '{}', 'dumbbell', false),
  ('Lying T-Bar Row', 'middle back', '{"biceps","lats"}', 'machine', false),
  ('Lying Triceps Press', 'triceps', '{}', 'e-z curl bar', false),
  ('Machine Bench Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Machine Bicep Curl', 'biceps', '{}', 'machine', false),
  ('Machine Preacher Curls', 'biceps', '{}', 'machine', false),
  ('Machine Shoulder (Military) Press', 'shoulders', '{"triceps"}', 'machine', false),
  ('Machine Triceps Extension', 'triceps', '{}', 'machine', false),
  ('Medicine Ball Chest Pass', 'chest', '{"shoulders","triceps"}', 'medicine ball', false),
  ('Medicine Ball Full Twist', 'abdominals', '{"shoulders"}', 'medicine ball', false),
  ('Medicine Ball Scoop Throw', 'shoulders', '{"abdominals","hamstrings","quadriceps"}', 'medicine ball', false),
  ('Middle Back Shrug', 'middle back', '{}', 'dumbbell', false),
  ('Middle Back Stretch', 'middle back', '{"abdominals","lats","lower back"}', null, false),
  ('Mixed Grip Chin', 'middle back', '{"biceps","lats"}', 'other', false),
  ('Monster Walk', 'abductors', '{}', 'bands', false),
  ('Mountain Climbers', 'quadriceps', '{"chest","hamstrings","shoulders"}', null, false),
  ('Moving Claw Series', 'hamstrings', '{"calves","quadriceps"}', null, false),
  ('Muscle Snatch', 'hamstrings', '{"glutes","lower back","quadriceps","shoulders","triceps"}', 'barbell', false),
  ('Muscle Up', 'lats', '{"abdominals","biceps","forearms","middle back","shoulders","traps","triceps"}', 'other', false),
  ('Narrow Stance Hack Squats', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Narrow Stance Leg Press', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Narrow Stance Squats', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Natural Glute Ham Raise', 'hamstrings', '{"calves","glutes","lower back"}', 'body only', false),
  ('Neck-SMR', 'neck', '{}', 'other', false),
  ('Neck Press', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Oblique Crunches', 'abdominals', '{}', 'body only', false),
  ('Oblique Crunches - On The Floor', 'abdominals', '{}', 'body only', false),
  ('Olympic Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('On-Your-Back Quad Stretch', 'quadriceps', '{}', 'other', false),
  ('On Your Side Quad Stretch', 'quadriceps', '{}', null, false),
  ('One-Arm Dumbbell Row', 'middle back', '{"biceps","lats","shoulders"}', 'dumbbell', false),
  ('One-Arm Flat Bench Dumbbell Flye', 'chest', '{}', 'dumbbell', false),
  ('One-Arm High-Pulley Cable Side Bends', 'abdominals', '{}', 'cable', false),
  ('One-Arm Incline Lateral Raise', 'shoulders', '{}', 'dumbbell', false),
  ('One-Arm Kettlebell Clean', 'hamstrings', '{"glutes","lower back","shoulders","traps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Clean and Jerk', 'shoulders', '{}', 'kettlebells', false),
  ('One-Arm Kettlebell Floor Press', 'chest', '{"triceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Jerk', 'shoulders', '{"calves","quadriceps","triceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Military Press To The Side', 'shoulders', '{"triceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Para Press', 'shoulders', '{"triceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Push Press', 'shoulders', '{"calves","quadriceps","triceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Row', 'middle back', '{"biceps","lats"}', 'kettlebells', false),
  ('One-Arm Kettlebell Snatch', 'shoulders', '{"calves","glutes","hamstrings","lower back","traps","triceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Split Jerk', 'shoulders', '{"glutes","hamstrings","quadriceps","triceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Split Snatch', 'shoulders', '{"hamstrings","quadriceps"}', 'kettlebells', false),
  ('One-Arm Kettlebell Swings', 'hamstrings', '{"calves","glutes","lower back","shoulders"}', 'kettlebells', false),
  ('One-Arm Long Bar Row', 'middle back', '{"biceps","lats"}', 'barbell', false),
  ('One-Arm Medicine Ball Slam', 'abdominals', '{"lats","shoulders"}', 'medicine ball', false),
  ('One-Arm Open Palm Kettlebell Clean', 'hamstrings', '{"forearms","glutes","lower back","quadriceps","shoulders"}', 'kettlebells', false),
  ('One-Arm Overhead Kettlebell Squats', 'quadriceps', '{"calves","glutes","hamstrings","shoulders"}', 'kettlebells', false),
  ('One-Arm Side Deadlift', 'quadriceps', '{"abdominals","calves","glutes","hamstrings","lower back","traps"}', 'barbell', false),
  ('One-Arm Side Laterals', 'shoulders', '{}', 'dumbbell', false),
  ('One-Legged Cable Kickback', 'glutes', '{"hamstrings"}', 'cable', false),
  ('One Arm Against Wall', 'lats', '{}', null, false),
  ('One Arm Chin-Up', 'middle back', '{"biceps","forearms","lats"}', 'other', false),
  ('One Arm Dumbbell Bench Press', 'chest', '{"shoulders","triceps"}', 'dumbbell', false),
  ('One Arm Dumbbell Preacher Curl', 'biceps', '{}', 'dumbbell', false),
  ('One Arm Floor Press', 'triceps', '{"chest","shoulders"}', 'barbell', false),
  ('One Arm Lat Pulldown', 'lats', '{"biceps","middle back"}', 'cable', false),
  ('One Arm Pronated Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('One Arm Supinated Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('One Half Locust', 'quadriceps', '{"abdominals","biceps","chest"}', null, false),
  ('One Handed Hang', 'lats', '{"biceps"}', 'other', false),
  ('One Knee To Chest', 'glutes', '{"hamstrings","lower back"}', null, false),
  ('One Leg Barbell Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Open Palm Kettlebell Clean', 'hamstrings', '{"glutes","lower back","quadriceps","shoulders"}', 'kettlebells', false),
  ('Otis-Up', 'abdominals', '{"chest","shoulders","triceps"}', 'other', false),
  ('Overhead Cable Curl', 'biceps', '{}', 'cable', false),
  ('Overhead Lat', 'lats', '{"triceps"}', 'other', false),
  ('Overhead Slam', 'lats', '{}', 'medicine ball', false),
  ('Overhead Squat', 'quadriceps', '{"abdominals","calves","glutes","hamstrings","lower back","shoulders","triceps"}', 'barbell', false),
  ('Overhead Stretch', 'abdominals', '{"chest","forearms","lats","triceps"}', null, false),
  ('Overhead Triceps', 'triceps', '{"lats"}', 'body only', false),
  ('Pallof Press', 'abdominals', '{"chest","shoulders","triceps"}', 'cable', false),
  ('Pallof Press With Rotation', 'abdominals', '{"chest","shoulders","triceps"}', 'cable', false),
  ('Palms-Down Dumbbell Wrist Curl Over A Bench', 'forearms', '{}', 'dumbbell', false),
  ('Palms-Down Wrist Curl Over A Bench', 'forearms', '{}', 'barbell', false),
  ('Palms-Up Barbell Wrist Curl Over A Bench', 'forearms', '{}', 'barbell', false),
  ('Palms-Up Dumbbell Wrist Curl Over A Bench', 'forearms', '{}', 'dumbbell', false),
  ('Parallel Bar Dip', 'triceps', '{"chest","shoulders"}', 'other', false),
  ('Pelvic Tilt Into Bridge', 'lower back', '{}', null, false),
  ('Peroneals-SMR', 'calves', '{}', 'foam roll', false),
  ('Peroneals Stretch', 'calves', '{}', 'other', false),
  ('Physioball Hip Bridge', 'glutes', '{"hamstrings"}', 'exercise ball', false),
  ('Pin Presses', 'triceps', '{"chest","forearms","lats","middle back","shoulders"}', 'barbell', false),
  ('Piriformis-SMR', 'glutes', '{}', 'foam roll', false),
  ('Plank', 'abdominals', '{}', 'body only', false),
  ('Plate Pinch', 'forearms', '{}', 'other', false),
  ('Plate Twist', 'abdominals', '{}', 'other', false),
  ('Platform Hamstring Slides', 'hamstrings', '{"glutes"}', 'other', false),
  ('Plie Dumbbell Squat', 'quadriceps', '{"abdominals","calves","glutes","hamstrings"}', 'dumbbell', false),
  ('Plyo Kettlebell Pushups', 'chest', '{"shoulders","triceps"}', 'kettlebells', false),
  ('Plyo Push-up', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Posterior Tibialis Stretch', 'calves', '{}', 'other', false),
  ('Power Clean', 'hamstrings', '{"calves","forearms","glutes","lower back","middle back","quadriceps","shoulders","traps","triceps"}', 'barbell', false),
  ('Power Clean from Blocks', 'hamstrings', '{"quadriceps"}', 'barbell', false),
  ('Power Jerk', 'quadriceps', '{"abdominals","calves","glutes","hamstrings","shoulders","triceps"}', 'barbell', false),
  ('Power Partials', 'shoulders', '{}', 'dumbbell', false),
  ('Power Snatch', 'hamstrings', '{"calves","glutes","lower back","quadriceps","shoulders","traps","triceps"}', 'barbell', false),
  ('Power Snatch from Blocks', 'quadriceps', '{"calves","forearms","glutes","hamstrings","lower back","shoulders","traps","triceps"}', 'barbell', false),
  ('Power Stairs', 'hamstrings', '{"adductors","calves","glutes","lower back","quadriceps","shoulders","traps"}', 'other', false),
  ('Preacher Curl', 'biceps', '{}', 'barbell', false),
  ('Preacher Hammer Dumbbell Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Press Sit-Up', 'abdominals', '{"chest","shoulders","triceps"}', 'barbell', false),
  ('Prone Manual Hamstring', 'hamstrings', '{}', null, false),
  ('Prowler Sprint', 'hamstrings', '{"calves","chest","glutes","quadriceps","shoulders"}', 'other', false),
  ('Pull Through', 'glutes', '{"hamstrings","lower back"}', 'cable', false),
  ('Pullups', 'lats', '{"biceps","middle back"}', 'body only', false),
  ('Push-Up Wide', 'chest', '{"abdominals","shoulders","triceps"}', 'body only', false),
  ('Push-Ups - Close Triceps Position', 'triceps', '{"chest","shoulders"}', 'body only', false),
  ('Push-Ups With Feet Elevated', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Push-Ups With Feet On An Exercise Ball', 'chest', '{"shoulders","triceps"}', 'exercise ball', false),
  ('Push Press', 'shoulders', '{"quadriceps","triceps"}', 'barbell', false),
  ('Push Press - Behind the Neck', 'shoulders', '{"calves","quadriceps","triceps"}', 'barbell', false),
  ('Push Up to Side Plank', 'chest', '{"abdominals","shoulders","triceps"}', 'body only', false),
  ('Pushups', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Pushups (Close and Wide Hand Positions)', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Pyramid', 'lower back', '{"shoulders"}', 'exercise ball', false),
  ('Quad Stretch', 'quadriceps', '{}', 'other', false),
  ('Quadriceps-SMR', 'quadriceps', '{}', 'foam roll', false),
  ('Quick Leap', 'quadriceps', '{"calves","hamstrings"}', 'other', false),
  ('Rack Delivery', 'shoulders', '{"forearms","traps"}', 'barbell', false),
  ('Rack Pull with Bands', 'lower back', '{"forearms","glutes","hamstrings","quadriceps","traps"}', 'barbell', false),
  ('Rack Pulls', 'lower back', '{"forearms","glutes","hamstrings","traps"}', 'barbell', false),
  ('Rear Leg Raises', 'quadriceps', '{}', 'body only', false),
  ('Recumbent Bike', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Return Push from Stance', 'shoulders', '{"chest","triceps"}', 'medicine ball', false),
  ('Reverse Band Bench Press', 'triceps', '{"chest","forearms","lats","middle back","shoulders"}', 'barbell', false),
  ('Reverse Band Box Squat', 'quadriceps', '{"abductors","adductors","calves","forearms","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Reverse Band Deadlift', 'lower back', '{"abductors","adductors","calves","glutes","hamstrings","quadriceps"}', 'barbell', false),
  ('Reverse Band Power Squat', 'quadriceps', '{"adductors","calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Reverse Band Sumo Deadlift', 'hamstrings', '{"abductors","adductors","calves","forearms","glutes","lower back","quadriceps","traps"}', 'barbell', false),
  ('Reverse Barbell Curl', 'biceps', '{"forearms"}', 'barbell', false),
  ('Reverse Barbell Preacher Curls', 'biceps', '{"forearms"}', 'e-z curl bar', false),
  ('Reverse Cable Curl', 'biceps', '{"forearms"}', 'cable', false),
  ('Reverse Crunch', 'abdominals', '{}', 'body only', false),
  ('Reverse Flyes', 'shoulders', '{}', 'dumbbell', false),
  ('Reverse Flyes With External Rotation', 'shoulders', '{}', 'dumbbell', false),
  ('Reverse Grip Bent-Over Rows', 'middle back', '{"biceps","lats","shoulders"}', 'barbell', false),
  ('Reverse Grip Triceps Pushdown', 'triceps', '{}', 'cable', false),
  ('Reverse Hyperextension', 'hamstrings', '{"calves","glutes"}', 'machine', false),
  ('Reverse Machine Flyes', 'shoulders', '{}', 'machine', false),
  ('Reverse Plate Curls', 'biceps', '{"forearms"}', 'other', false),
  ('Reverse Triceps Bench Press', 'triceps', '{"chest","shoulders"}', 'barbell', false),
  ('Rhomboids-SMR', 'middle back', '{"traps"}', 'foam roll', false),
  ('Rickshaw Carry', 'forearms', '{"abdominals","calves","glutes","hamstrings","lower back","quadriceps","traps"}', 'other', false),
  ('Rickshaw Deadlift', 'quadriceps', '{"forearms","glutes","hamstrings","lower back","traps"}', 'other', false),
  ('Ring Dips', 'triceps', '{"chest","shoulders"}', 'other', false),
  ('Rocket Jump', 'quadriceps', '{"calves","hamstrings"}', 'body only', false),
  ('Rocking Standing Calf Raise', 'calves', '{}', 'barbell', false),
  ('Rocky Pull-Ups/Pulldowns', 'lats', '{"biceps","middle back","shoulders"}', 'other', false),
  ('Romanian Deadlift', 'hamstrings', '{"calves","glutes","lower back"}', 'barbell', false),
  ('Romanian Deadlift from Deficit', 'hamstrings', '{"forearms","glutes","lower back","traps"}', 'barbell', false),
  ('Rope Climb', 'lats', '{"biceps","forearms","middle back","shoulders"}', 'other', false),
  ('Rope Crunch', 'abdominals', '{}', 'cable', false),
  ('Rope Jumping', 'quadriceps', '{"calves","hamstrings"}', 'other', false),
  ('Rope Straight-Arm Pulldown', 'lats', '{}', 'cable', false),
  ('Round The World Shoulder Stretch', 'shoulders', '{"biceps","chest"}', 'other', false),
  ('Rowing, Stationary', 'quadriceps', '{"biceps","calves","glutes","hamstrings","lower back","middle back"}', 'machine', false),
  ('Runner''s Stretch', 'hamstrings', '{"calves"}', null, false),
  ('Running, Treadmill', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Russian Twist', 'abdominals', '{"lower back"}', 'body only', false),
  ('Sandbag Load', 'quadriceps', '{"abdominals","biceps","calves","forearms","glutes","hamstrings","lower back","middle back","shoulders","traps"}', 'other', false),
  ('Scapular Pull-Up', 'traps', '{"lats","middle back"}', null, false),
  ('Scissor Kick', 'abdominals', '{}', 'body only', false),
  ('Scissors Jump', 'quadriceps', '{"glutes","hamstrings"}', 'body only', false),
  ('Seated Band Hamstring Curl', 'hamstrings', '{}', 'other', false),
  ('Seated Barbell Military Press', 'shoulders', '{"triceps"}', 'barbell', false),
  ('Seated Barbell Twist', 'abdominals', '{}', 'barbell', false),
  ('Seated Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('Seated Bent-Over Rear Delt Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Seated Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('Seated Biceps', 'biceps', '{"chest","shoulders"}', 'body only', false),
  ('Seated Cable Rows', 'middle back', '{"biceps","lats","shoulders"}', 'cable', false),
  ('Seated Cable Shoulder Press', 'shoulders', '{"triceps"}', 'cable', false),
  ('Seated Calf Raise', 'calves', '{}', 'machine', false),
  ('Seated Calf Stretch', 'calves', '{"hamstrings","lower back"}', null, false),
  ('Seated Close-Grip Concentration Barbell Curl', 'biceps', '{}', 'barbell', false),
  ('Seated Dumbbell Curl', 'biceps', '{}', 'dumbbell', false),
  ('Seated Dumbbell Inner Biceps Curl', 'biceps', '{}', 'dumbbell', false),
  ('Seated Dumbbell Palms-Down Wrist Curl', 'forearms', '{}', 'dumbbell', false),
  ('Seated Dumbbell Palms-Up Wrist Curl', 'forearms', '{}', 'dumbbell', false),
  ('Seated Dumbbell Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Seated Flat Bench Leg Pull-In', 'abdominals', '{}', 'body only', false),
  ('Seated Floor Hamstring Stretch', 'hamstrings', '{"calves"}', null, false),
  ('Seated Front Deltoid', 'shoulders', '{"chest"}', 'body only', false),
  ('Seated Glute', 'glutes', '{"adductors"}', 'body only', false),
  ('Seated Good Mornings', 'lower back', '{"glutes"}', 'barbell', false),
  ('Seated Hamstring', 'hamstrings', '{"calves"}', null, false),
  ('Seated Hamstring and Calf Stretch', 'hamstrings', '{"calves"}', 'other', false),
  ('Seated Head Harness Neck Resistance', 'neck', '{}', 'other', false),
  ('Seated Leg Curl', 'hamstrings', '{}', 'machine', false),
  ('Seated Leg Tucks', 'abdominals', '{}', 'body only', false),
  ('Seated One-Arm Dumbbell Palms-Down Wrist Curl', 'forearms', '{}', 'dumbbell', false),
  ('Seated One-Arm Dumbbell Palms-Up Wrist Curl', 'forearms', '{}', 'dumbbell', false),
  ('Seated One-arm Cable Pulley Rows', 'middle back', '{"biceps","lats","traps"}', 'cable', false),
  ('Seated Overhead Stretch', 'abdominals', '{}', null, false),
  ('Seated Palm-Up Barbell Wrist Curl', 'forearms', '{}', 'barbell', false),
  ('Seated Palms-Down Barbell Wrist Curl', 'forearms', '{}', 'barbell', false),
  ('Seated Side Lateral Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Seated Triceps Press', 'triceps', '{}', 'dumbbell', false),
  ('Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', 'forearms', '{}', 'cable', false),
  ('See-Saw Press (Alternating Side Press)', 'shoulders', '{"abdominals","triceps"}', 'dumbbell', false),
  ('Shotgun Row', 'lats', '{"biceps","middle back"}', 'cable', false),
  ('Shoulder Circles', 'shoulders', '{"traps"}', null, false),
  ('Shoulder Press - With Bands', 'shoulders', '{"triceps"}', 'bands', false),
  ('Shoulder Raise', 'shoulders', '{"lats"}', null, false),
  ('Shoulder Stretch', 'shoulders', '{}', null, false),
  ('Side-Lying Floor Stretch', 'lats', '{}', null, false),
  ('Side Bridge', 'abdominals', '{"shoulders"}', 'body only', false),
  ('Side Hop-Sprint', 'quadriceps', '{"abductors","adductors","calves","hamstrings"}', 'other', false),
  ('Side Jackknife', 'abdominals', '{}', 'body only', false),
  ('Side Lateral Raise', 'shoulders', '{}', 'dumbbell', false),
  ('Side Laterals to Front Raise', 'shoulders', '{"traps"}', 'dumbbell', false),
  ('Side Leg Raises', 'adductors', '{}', 'body only', false),
  ('Side Lying Groin Stretch', 'adductors', '{"hamstrings"}', null, false),
  ('Side Neck Stretch', 'neck', '{}', null, false),
  ('Side Standing Long Jump', 'quadriceps', '{"calves","glutes","hamstrings"}', null, false),
  ('Side To Side Chins', 'lats', '{"biceps","forearms","middle back","shoulders"}', 'other', false),
  ('Side Wrist Pull', 'shoulders', '{"forearms","lats"}', null, false),
  ('Side to Side Box Shuffle', 'quadriceps', '{"abductors","adductors","calves","hamstrings"}', 'other', false),
  ('Single-Arm Cable Crossover', 'chest', '{}', 'cable', false),
  ('Single-Arm Linear Jammer', 'shoulders', '{"chest","triceps"}', 'barbell', false),
  ('Single-Arm Push-Up', 'chest', '{"shoulders","triceps"}', 'body only', false),
  ('Single-Cone Sprint Drill', 'quadriceps', '{"calves","glutes","hamstrings"}', 'other', false),
  ('Single-Leg High Box Squat', 'quadriceps', '{"glutes","hamstrings"}', 'other', false),
  ('Single-Leg Hop Progression', 'quadriceps', '{"abductors","adductors","calves","hamstrings"}', 'other', false),
  ('Single-Leg Lateral Hop', 'quadriceps', '{"abductors","adductors","calves","hamstrings"}', 'other', false),
  ('Single-Leg Leg Extension', 'quadriceps', '{}', 'machine', false),
  ('Single-Leg Stride Jump', 'quadriceps', '{"abductors","adductors","calves","hamstrings"}', 'other', false),
  ('Single Dumbbell Raise', 'shoulders', '{"forearms","traps"}', 'dumbbell', false),
  ('Single Leg Butt Kick', 'quadriceps', '{"calves","hamstrings"}', 'body only', false),
  ('Single Leg Glute Bridge', 'glutes', '{"hamstrings"}', 'body only', false),
  ('Single Leg Push-off', 'quadriceps', '{"calves","hamstrings"}', 'other', false),
  ('Sit-Up', 'abdominals', '{}', 'body only', false),
  ('Sit Squats', 'quadriceps', '{"abductors","glutes","hamstrings"}', null, false),
  ('Skating', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', 'other', false),
  ('Sled Drag - Harness', 'quadriceps', '{"calves","glutes","hamstrings"}', 'other', false),
  ('Sled Overhead Backward Walk', 'shoulders', '{"calves","middle back","quadriceps"}', 'other', false),
  ('Sled Overhead Triceps Extension', 'triceps', '{}', 'other', false),
  ('Sled Push', 'quadriceps', '{"calves","chest","glutes","hamstrings","triceps"}', 'other', false),
  ('Sled Reverse Flye', 'shoulders', '{}', 'other', false),
  ('Sled Row', 'middle back', '{"biceps","lats"}', 'other', false),
  ('Sledgehammer Swings', 'abdominals', '{"calves","forearms","lats","middle back","shoulders"}', 'other', false),
  ('Smith Incline Shoulder Raise', 'shoulders', '{"chest"}', 'barbell', false),
  ('Smith Machine Behind the Back Shrug', 'traps', '{"shoulders"}', 'machine', false),
  ('Smith Machine Bench Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Smith Machine Bent Over Row', 'middle back', '{"biceps","lats","shoulders"}', 'machine', false),
  ('Smith Machine Calf Raise', 'calves', '{}', 'machine', false),
  ('Smith Machine Close-Grip Bench Press', 'triceps', '{"chest","shoulders"}', 'machine', false),
  ('Smith Machine Decline Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Smith Machine Hang Power Clean', 'hamstrings', '{"glutes","lower back","quadriceps","shoulders","traps"}', 'machine', false),
  ('Smith Machine Hip Raise', 'abdominals', '{}', 'machine', false),
  ('Smith Machine Incline Bench Press', 'chest', '{"shoulders","triceps"}', 'machine', false),
  ('Smith Machine Leg Press', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Smith Machine One-Arm Upright Row', 'shoulders', '{"biceps","traps"}', 'machine', false),
  ('Smith Machine Overhead Shoulder Press', 'shoulders', '{"triceps"}', 'machine', false),
  ('Smith Machine Pistol Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Smith Machine Reverse Calf Raises', 'calves', '{}', 'machine', false),
  ('Smith Machine Squat', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'machine', false),
  ('Smith Machine Stiff-Legged Deadlift', 'hamstrings', '{"glutes","lower back"}', 'machine', false),
  ('Smith Machine Upright Row', 'traps', '{"biceps","middle back","shoulders"}', 'machine', false),
  ('Smith Single-Leg Split Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Snatch', 'quadriceps', '{"biceps","glutes","hamstrings","lower back","shoulders","traps","triceps"}', 'barbell', false),
  ('Snatch Balance', 'quadriceps', '{"calves","glutes","hamstrings","shoulders","triceps"}', 'barbell', false),
  ('Snatch Deadlift', 'hamstrings', '{"forearms","glutes","hamstrings","lower back","quadriceps","traps"}', 'barbell', false),
  ('Snatch Pull', 'hamstrings', '{"calves","glutes","lower back","quadriceps","traps"}', 'barbell', false),
  ('Snatch Shrug', 'traps', '{"forearms","shoulders"}', 'barbell', false),
  ('Snatch from Blocks', 'quadriceps', '{"calves","forearms","glutes","hamstrings","lower back","shoulders","traps","triceps"}', 'barbell', false),
  ('Speed Band Overhead Triceps', 'triceps', '{}', 'bands', false),
  ('Speed Box Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Speed Squats', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Spell Caster', 'abdominals', '{"glutes","shoulders"}', 'dumbbell', false),
  ('Spider Crawl', 'abdominals', '{"chest","shoulders","triceps"}', 'body only', false),
  ('Spider Curl', 'biceps', '{}', 'e-z curl bar', false),
  ('Spinal Stretch', 'middle back', '{"lats","lower back","neck","traps"}', null, false),
  ('Split Clean', 'quadriceps', '{"calves","forearms","glutes","hamstrings","lower back","shoulders","traps"}', 'barbell', false),
  ('Split Jerk', 'quadriceps', '{"glutes","hamstrings","shoulders","triceps"}', 'barbell', false),
  ('Split Jump', 'quadriceps', '{"calves","glutes","hamstrings"}', 'body only', false),
  ('Split Snatch', 'hamstrings', '{"calves","forearms","glutes","hamstrings","lower back","quadriceps","shoulders","traps","triceps"}', 'barbell', false),
  ('Split Squat with Dumbbells', 'quadriceps', '{"glutes","hamstrings"}', 'dumbbell', false),
  ('Split Squats', 'hamstrings', '{"calves","glutes","quadriceps"}', null, false),
  ('Squat Jerk', 'quadriceps', '{"calves","glutes","hamstrings","shoulders","triceps"}', 'barbell', false),
  ('Squat with Bands', 'quadriceps', '{"adductors","calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Squat with Chains', 'quadriceps', '{"adductors","calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Squat with Plate Movers', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', 'barbell', false),
  ('Squats - With Bands', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'bands', false),
  ('Stairmaster', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Standing Alternating Dumbbell Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Standing Barbell Calf Raise', 'calves', '{}', 'barbell', false),
  ('Standing Barbell Press Behind Neck', 'shoulders', '{"triceps"}', 'barbell', false),
  ('Standing Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', '{"shoulders"}', 'dumbbell', false),
  ('Standing Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('Standing Biceps Cable Curl', 'biceps', '{}', 'cable', false),
  ('Standing Biceps Stretch', 'biceps', '{"chest","shoulders"}', 'other', false),
  ('Standing Bradford Press', 'shoulders', '{"triceps"}', 'barbell', false),
  ('Standing Cable Chest Press', 'chest', '{"shoulders","triceps"}', 'cable', false),
  ('Standing Cable Lift', 'abdominals', '{"shoulders"}', 'cable', false),
  ('Standing Cable Wood Chop', 'abdominals', '{"shoulders"}', 'cable', false),
  ('Standing Calf Raises', 'calves', '{}', 'machine', false),
  ('Standing Concentration Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Standing Dumbbell Calf Raise', 'calves', '{}', 'dumbbell', false),
  ('Standing Dumbbell Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Standing Dumbbell Reverse Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Standing Dumbbell Straight-Arm Front Delt Raise Above Head', 'shoulders', '{}', 'dumbbell', false),
  ('Standing Dumbbell Triceps Extension', 'triceps', '{}', 'dumbbell', false),
  ('Standing Dumbbell Upright Row', 'traps', '{"biceps","shoulders"}', 'dumbbell', false),
  ('Standing Elevated Quad Stretch', 'quadriceps', '{}', 'other', false),
  ('Standing Front Barbell Raise Over Head', 'shoulders', '{}', 'barbell', false),
  ('Standing Gastrocnemius Calf Stretch', 'calves', '{"hamstrings"}', null, false),
  ('Standing Hamstring and Calf Stretch', 'hamstrings', '{}', 'other', false),
  ('Standing Hip Circles', 'abductors', '{"adductors"}', 'body only', false),
  ('Standing Hip Flexors', 'quadriceps', '{}', null, false),
  ('Standing Inner-Biceps Curl', 'biceps', '{}', 'dumbbell', false),
  ('Standing Lateral Stretch', 'abdominals', '{}', null, false),
  ('Standing Leg Curl', 'hamstrings', '{}', 'machine', false),
  ('Standing Long Jump', 'quadriceps', '{"calves","glutes","hamstrings"}', 'body only', false),
  ('Standing Low-Pulley Deltoid Raise', 'shoulders', '{"forearms"}', 'cable', false),
  ('Standing Low-Pulley One-Arm Triceps Extension', 'triceps', '{"chest","shoulders"}', 'cable', false),
  ('Standing Military Press', 'shoulders', '{"triceps"}', 'barbell', false),
  ('Standing Olympic Plate Hand Squeeze', 'forearms', '{"biceps"}', 'other', false),
  ('Standing One-Arm Cable Curl', 'biceps', '{}', 'cable', false),
  ('Standing One-Arm Dumbbell Curl Over Incline Bench', 'biceps', '{}', 'dumbbell', false),
  ('Standing One-Arm Dumbbell Triceps Extension', 'triceps', '{"chest","shoulders"}', 'dumbbell', false),
  ('Standing Overhead Barbell Triceps Extension', 'triceps', '{"shoulders"}', 'barbell', false),
  ('Standing Palm-In One-Arm Dumbbell Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Standing Palms-In Dumbbell Press', 'shoulders', '{"triceps"}', 'dumbbell', false),
  ('Standing Palms-Up Barbell Behind The Back Wrist Curl', 'forearms', '{}', 'barbell', false),
  ('Standing Pelvic Tilt', 'lower back', '{"glutes"}', null, false),
  ('Standing Rope Crunch', 'abdominals', '{}', 'cable', false),
  ('Standing Soleus And Achilles Stretch', 'calves', '{}', null, false),
  ('Standing Toe Touches', 'hamstrings', '{"calves"}', null, false),
  ('Standing Towel Triceps Extension', 'triceps', '{}', 'body only', false),
  ('Standing Two-Arm Overhead Throw', 'shoulders', '{"chest","lats"}', 'medicine ball', false),
  ('Star Jump', 'quadriceps', '{"calves","glutes","hamstrings","shoulders"}', 'body only', false),
  ('Step-up with Knee Raise', 'glutes', '{"hamstrings","quadriceps"}', 'body only', false),
  ('Step Mill', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Stiff-Legged Barbell Deadlift', 'hamstrings', '{"glutes","lower back"}', 'barbell', false),
  ('Stiff-Legged Dumbbell Deadlift', 'hamstrings', '{"glutes","lower back"}', 'dumbbell', false),
  ('Stiff Leg Barbell Good Morning', 'lower back', '{"glutes","hamstrings"}', 'barbell', false),
  ('Stomach Vacuum', 'abdominals', '{}', 'body only', false),
  ('Straight-Arm Dumbbell Pullover', 'chest', '{"lats","shoulders","triceps"}', 'dumbbell', false),
  ('Straight-Arm Pulldown', 'lats', '{}', 'cable', false),
  ('Straight Bar Bench Mid Rows', 'middle back', '{"biceps","lats"}', 'barbell', false),
  ('Straight Raises on Incline Bench', 'shoulders', '{"traps"}', 'barbell', false),
  ('Stride Jump Crossover', 'quadriceps', '{"abductors","adductors","calves","hamstrings"}', 'other', false),
  ('Sumo Deadlift', 'hamstrings', '{"adductors","forearms","glutes","lower back","middle back","quadriceps","traps"}', 'barbell', false),
  ('Sumo Deadlift with Bands', 'hamstrings', '{"adductors","forearms","glutes","lower back","middle back","quadriceps","traps"}', 'barbell', false),
  ('Sumo Deadlift with Chains', 'hamstrings', '{"abductors","adductors","forearms","glutes","lower back","middle back","quadriceps","traps"}', 'barbell', false),
  ('Superman', 'lower back', '{"glutes","hamstrings"}', 'body only', false),
  ('Supine Chest Throw', 'triceps', '{"chest","shoulders"}', 'medicine ball', false),
  ('Supine One-Arm Overhead Throw', 'abdominals', '{"chest","lats","shoulders"}', 'medicine ball', false),
  ('Supine Two-Arm Overhead Throw', 'abdominals', '{"chest","lats","shoulders"}', 'medicine ball', false),
  ('Suspended Fallout', 'abdominals', '{"chest","lower back","shoulders"}', 'other', false),
  ('Suspended Push-Up', 'chest', '{"shoulders","triceps"}', 'other', false),
  ('Suspended Reverse Crunch', 'abdominals', '{}', 'other', false),
  ('Suspended Row', 'middle back', '{"biceps","lats"}', 'other', false),
  ('Suspended Split Squat', 'quadriceps', '{"abductors","adductors","calves","glutes","hamstrings"}', 'other', false),
  ('Svend Press', 'chest', '{"forearms","shoulders","triceps"}', 'other', false),
  ('T-Bar Row with Handle', 'middle back', '{"biceps","lats"}', 'barbell', false),
  ('Tate Press', 'triceps', '{"chest","shoulders"}', 'dumbbell', false),
  ('The Straddle', 'hamstrings', '{"adductors","calves"}', null, false),
  ('Thigh Abductor', 'abductors', '{"glutes"}', 'machine', false),
  ('Thigh Adductor', 'adductors', '{"glutes","hamstrings"}', 'machine', false),
  ('Tire Flip', 'quadriceps', '{"calves","chest","forearms","glutes","hamstrings","lower back","shoulders","traps","triceps"}', 'other', false),
  ('Toe Touchers', 'abdominals', '{}', 'body only', false),
  ('Torso Rotation', 'abdominals', '{}', 'exercise ball', false),
  ('Trail Running/Walking', 'quadriceps', '{"calves","glutes","hamstrings"}', null, false),
  ('Trap Bar Deadlift', 'quadriceps', '{"glutes","hamstrings"}', 'other', false),
  ('Tricep Dumbbell Kickback', 'triceps', '{}', 'dumbbell', false),
  ('Tricep Side Stretch', 'triceps', '{"shoulders"}', null, false),
  ('Triceps Overhead Extension with Rope', 'triceps', '{}', 'cable', false),
  ('Triceps Pushdown', 'triceps', '{}', 'cable', false),
  ('Triceps Pushdown - Rope Attachment', 'triceps', '{}', 'cable', false),
  ('Triceps Pushdown - V-Bar Attachment', 'triceps', '{}', 'cable', false),
  ('Triceps Stretch', 'triceps', '{"lats"}', null, false),
  ('Tuck Crunch', 'abdominals', '{}', 'body only', false),
  ('Two-Arm Dumbbell Preacher Curl', 'biceps', '{}', 'dumbbell', false),
  ('Two-Arm Kettlebell Clean', 'shoulders', '{"calves","glutes","hamstrings","lower back","traps"}', 'kettlebells', false),
  ('Two-Arm Kettlebell Jerk', 'shoulders', '{"calves","quadriceps","triceps"}', 'kettlebells', false),
  ('Two-Arm Kettlebell Military Press', 'shoulders', '{"triceps"}', 'kettlebells', false),
  ('Two-Arm Kettlebell Row', 'middle back', '{"biceps","lats"}', 'kettlebells', false),
  ('Underhand Cable Pulldowns', 'lats', '{"biceps","middle back","shoulders"}', 'cable', false),
  ('Upper Back-Leg Grab', 'hamstrings', '{"lower back","middle back"}', null, false),
  ('Upper Back Stretch', 'middle back', '{"middle back"}', null, false),
  ('Upright Barbell Row', 'shoulders', '{"traps"}', 'barbell', false),
  ('Upright Cable Row', 'traps', '{"shoulders"}', 'cable', false),
  ('Upright Row - With Bands', 'traps', '{"shoulders"}', 'bands', false),
  ('Upward Stretch', 'shoulders', '{"chest","lats"}', null, false),
  ('V-Bar Pulldown', 'lats', '{"biceps","middle back","shoulders"}', 'cable', false),
  ('V-Bar Pullup', 'lats', '{"biceps","middle back","shoulders"}', 'body only', false),
  ('Vertical Swing', 'hamstrings', '{"glutes","quadriceps","shoulders"}', 'dumbbell', false),
  ('Walking, Treadmill', 'quadriceps', '{"calves","glutes","hamstrings"}', 'machine', false),
  ('Weighted Ball Hyperextension', 'lower back', '{"glutes","hamstrings","middle back"}', 'exercise ball', false),
  ('Weighted Ball Side Bend', 'abdominals', '{}', 'exercise ball', false),
  ('Weighted Bench Dip', 'triceps', '{"chest","shoulders"}', 'other', false),
  ('Weighted Crunches', 'abdominals', '{}', 'medicine ball', false),
  ('Weighted Jump Squat', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Weighted Pull Ups', 'lats', '{"biceps","middle back"}', 'other', false),
  ('Weighted Sissy Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Weighted Sit-Ups - With Bands', 'abdominals', '{}', 'other', false),
  ('Weighted Squat', 'quadriceps', '{"calves","glutes","hamstrings"}', 'other', false),
  ('Wide-Grip Barbell Bench Press', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Wide-Grip Decline Barbell Bench Press', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Wide-Grip Decline Barbell Pullover', 'chest', '{"shoulders","triceps"}', 'barbell', false),
  ('Wide-Grip Lat Pulldown', 'lats', '{"biceps","middle back","shoulders"}', 'cable', false),
  ('Wide-Grip Pulldown Behind The Neck', 'lats', '{"biceps","middle back","shoulders"}', 'cable', false),
  ('Wide-Grip Rear Pull-Up', 'lats', '{"biceps","middle back","shoulders"}', 'body only', false),
  ('Wide-Grip Standing Barbell Curl', 'biceps', '{}', 'barbell', false),
  ('Wide Stance Barbell Squat', 'quadriceps', '{"calves","glutes","hamstrings","lower back"}', 'barbell', false),
  ('Wide Stance Stiff Legs', 'hamstrings', '{"adductors","glutes","lower back"}', 'barbell', false),
  ('Wind Sprints', 'abdominals', '{}', 'body only', false),
  ('Windmills', 'abductors', '{"glutes","hamstrings","lower back"}', null, false),
  ('World''s Greatest Stretch', 'hamstrings', '{"calves","glutes","quadriceps"}', null, false),
  ('Wrist Circles', 'forearms', '{}', 'body only', false),
  ('Wrist Roller', 'forearms', '{"shoulders"}', 'other', false),
  ('Wrist Rotations with Straight Bar', 'forearms', '{}', 'barbell', false),
  ('Yoke Walk', 'quadriceps', '{"abdominals","abductors","adductors","calves","glutes","hamstrings","lower back"}', 'other', false),
  ('Zercher Squats', 'quadriceps', '{"calves","glutes","hamstrings"}', 'barbell', false),
  ('Zottman Curl', 'biceps', '{"forearms"}', 'dumbbell', false),
  ('Zottman Preacher Curl', 'biceps', '{"forearms"}', 'dumbbell', false);
